### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
### OCR 요청 (이미지 + 옵션 포함)   :  아래 {{}} 안에 있는 템플릿 변수는 intellij가 자동생성함.
POST http://test:8080/api/ocr
Content-Type: application/json

{
  "version": "V1",
  "requestId": "{{uuid}}",
  "timestamp": {{timestamp}},
  "images": [
    {
      "format": "jpg",
      "data": "{{file(\"d:/test/1.jpg\", \"base64\")}}",
      "name": "1.jpg",
      "option": {
        "pageRange": [0]
      }
    }
  ],
  "details": "text"
}
