spring:
    main:
        web-application-type: none
        banner-mode: off
    application:
        name: lg
    datasource:
        url: jdbc:mysql://192.168.14.112:3306/movies
        username: root
        password: pass123#
        driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-handlers-package: com.rayful.lgpoc.gathering.util
    configuration:
        map-underscore-to-camel-case: true

logging:
    level:
        root: INFO
#        root: DEBUG
#        org.springframework.web: WARN
    file:
        name: /data/poc/bulker/logs/application.log

########################## Application Specific Variables ##################################
app:
    paths:
        input:
            raw_emails: /data/poc/bulker/input/raw_emails            #(elm 파일), 대용량 메일 첨부 형식 (네이버 대용량 첨부링크)
            emails: /data/poc/bulker/input/emails            # 이메일형식의 json 파일(파싱처리됨, by 소만사)
            files: /data/poc/bulker/input/files
            download: /data/poc/bulker/input/download
            images: /data/poc/bulker/input/images
        output:
            bulkfiles: /data/poc/bulker/output/bulkfiles
            merged: /data/poc/bulker/output/merged
        attachments: /data/poc/attachments
        synap_exe: /data/poc/bulker/synap/v4/snf_exe

    file:
        timestamp: /data/poc/bulker/timestamp/last_executed.txt
    bulk:
        size: 100

elasticsearch:
#        bulk_idx_url: http://122.199.202.101:9200/idx_email/_bulk
#        idx_refresh: http://122.199.202.101:9200/idx_email/_refresh
        bulk_idx_url: http://192.168.14.112:9200/idx_email/_bulk
        idx_refresh: http://192.168.14.112:9200/idx_email/_refresh
        auth: elastic:elastic
ocr:
    edentns:
        #ocr_api_url: https://ocr.edentns.ai/document/general
        ocr_api_url: http://192.168.14.111:8000/document/general
    output_path:
        image: /data/poc/bulker/output/synap/image
        text: /data/poc/bulker/output/synap/text


