spring:
    main:
        web-application-type: none
        banner-mode: off
    application:
        name: lg
#    datasource:
#        url: jdbc:mysql://122.199.202.100:13306/movies
#        username: root
#        password: pass123#
#        driver-class-name: com.mysql.cj.jdbc.Driver
    datasource:
        url: jdbc:mysql://122.199.202.101:3306/lgcns_admin
        username: root
        password: pass123#
        driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
    mapper-locations: classpath:mappers/*.xml
    type-handlers-package: com.rayful.lgpoc.gathering.util
    type-aliases-package: com.rayful.lgbulker.entity
    configuration:
        map-underscore-to-camel-case: true

#sftp:
#    host: 192.168.56.111
#    port: 22
#    username: kevin
#    password: pass123#
#    remote-directory: /data/lgpoc/attachments
#    local-directory: /data/poc/bulker/attachments
#    cron: "0 0/10 * * * *"  # 10분마다


logging:
    level:
        root: INFO
#        root: DEBUG
#        org.springframework.web: WARN
    file:
        name: D:/1.data_poc/logs/application.log


########################## Application Specific Variables ##################################
app:
    paths:
        input:
            raw_emails: D:\1.data_poc\input\raw_emails            #(elm 파일), 대용량 메일 첨부 형식 (네이버 대용량 첨부링크)
            emails: D:\1.data_poc\input\emails                      # 이메일형식의 json 파일(파싱처리됨, by 소만사)
            files: D:\1.data_poc\input\files
            download: D:\1.data_poc\input\download
            images: D:\1.data_poc\input\images
        output:
            bulkfiles: D:\1.data_poc\output\bulkfiles
            merged: D:\1.data_poc\output\merged
        attachments: D:\1.data_poc\attachments
        synap_exe: D:\1.data_poc\synap_v4\snf_exe.exe

    file:
        timestamp: D:\1.data_poc\timestamp\last_executed.txt
        lock: D:\1.data_poc\lock\bulker.lck
    bulk:
        size: 100

elasticsearch:
        bulk_idx_url: http://122.199.202.101:9200/idx_email/_bulk
        idx_refresh: http://122.199.202.101:9200/idx_email/_refresh
        auth: elastic:elastic

ocr:
    edentns:
        ocr_api_url: https://ocr.edentns.ai/document/general
    output_path:
        image: D:\1.data_poc\output\synap\image
        text: D:\1.data_poc\output\synap\text



